name: my workflow with var 2
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - run: echo "build"
  deploy:
   needs: build
   runs-on: ubuntu-latest
   steps:
    - run: echo "deploy in prod"
